version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/meowsenger-frontend
      args:
        - NPM_CONFIG_LEGACY_PEER_DEPS=true
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/meowsenger-frontend/.env
    networks:
      - meowsenger-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=http://localhost:8081/ws
      - NPM_CONFIG_LEGACY_PEER_DEPS=true

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=db # Explicitly set this to override .env file in Docker environment
      - DEBUG=True
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=sqlite:///db.sqlite3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - meowsenger-network

  websocket:
    build:
      context: ./messaging
    ports:
      - "8081:8081"
    volumes:
      - ./messaging:/app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8081
    depends_on:
      - backend
    networks:
      - meowsenger-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=meowsenger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meowsenger-network

networks:
  meowsenger-network:
    driver: bridge

volumes:
  postgres_data:
