const kg = {
  // Навигация
  chats: "баарлашуулар",
  profile: "профиль",
  settings: "жөндөөлөр",
  logout: "чыгуу",
  games: "оюндар",
  // Башкы бет
  home_title: "meowsenger менен баарлашыңыз",
  home_subtitle: "кооз, тез жана заманбап мессенджер",
  start_messaging: "баарлашууну баштоо",
  signing_up: "катталуу",
  already_have_account: "аккаунтуңуз барбы?",
  // Авторизация
  login: "кирүү",
  signup: "катталуу",
  username: "колдонуучу аты",
  password: "сырсөз",
  confirm_password: "сырсөздү тастыктаңыз",
  login_here: "бул жерден кириңиз",
  signup_here: "бул жерден катталыңыз",
  choose_username: "колдонуучу атын тандаңыз",
  create_password: "сырсөз түзүңүз",
  confirm_your_password: "сырсөзүңүздү тастыктаңыз",
  your_username: "колдонуучу атыңыз",
  your_password: "сырсөзүңүз",
  login_to_meowsenger: "meowsenger'ге кирүү",
  welcome_back_enter_credentials:
    "кайра келгениңиз менен! маалыматтарыңызды киргизиңиз",
  log_in: "кирүү",
  dont_have_account: "аккаунтуңуз жокпу?",
  create_account_to_start_messaging: "баарлашуу үчүн аккаунт түзүңүз",
  creating_account: "аккаунт түзүлүүдө...",
  logging_in: "кирүү...",

  // Аутентификация каталар
  error_password_too_short: "сырсөз кеминде 8 символдон турушу керек",
  error_password_too_common: "сырсөз өтө жөнөкөй же табылгыч",
  error_password_entirely_numeric: "сырсөз жалаң сандардан турбашы керек",
  error_password_similar_to_personal: "сырсөз жеке маалыматыңызга өтө окшош",
  error_passwords_dont_match: "сырсөздөр дал келбейт",
  error_username_taken: "бул колдонуучу аты бош эмес",
  error_invalid_credentials: "колдонуучу аты же сырсөз туура эмес",
  error_authentication_failed:
    "аутентификация ийгиликсиз, кайра аракет кылыңыз",
  error_registration_failed:
    "каттоо ийгиликсиз, маалыматтарыңызды текшерип, кайра аракет кылыңыз",
  error_server: "сервер катасы, бир аздан кийин кайра аракет кылыңыз",

  // Профиль
  edit_profile: "профилди өзгөртүү",
  save: "сактоо",
  cancel: "жокко чыгаруу",
  username_placeholder: "колдонуучу атын киргизиңиз",
  description_placeholder: "кыскача маалымат киргизиңиз",
  // Чат
  back: "артка",
  admin: "админ",
  tester: "тестировщик",
  no_messages: "али билдирүү жок. сүйлөшүүнү баштаңыз!",
  no_messages_short: "билдирүү жок",
  this_message_was_deleted: "бул билдирүү өчүрүлдү",
  edited: "өзгөртүлдү",
  edited_short: "(өзгөртүлдү)",
  type_a_message: "билдирүүнү жазыңыз...",
  send: "жөнөтүү",
  loading_conversation: "баарлашуу жүктөлүүдө...",
  conversation_not_found: "баарлашуу табылган жок же сизде ага уруксат жок.",
  back_to_chats: "баарлашууларга кайтуу",
  // Билдирүү аракеттери
  copy: "көчүрүү",
  reply: "жооп берүү",
  forward: "бөлүшүү",
  edit: "түзөтүү",
  delete: "өчүрүү",
  // Билдирүү жазуу
  edit_your_message: "билдирүүнү түзөтүңүз...",
  reconnecting: "кайра туташууда...",
  connected: "туташкан",
  disconnected: "ажыратылган",
  // Билдирүү тизмеси
  load_older_messages: "эски билдирүүлөрдү жүктөө",
  is_typing: "жазып жатат...",
  are_typing: "{count} колдонуучу жазып жатат...",
  replying_to: "жооп берүү",
  replying_to_self: "өзүңүзгө жооп берип жатасыз",
  reply_to_user: "{user} колдонуучуга жооп берүү",
  editing_message: "билдирүү түзөтүлүүдө: {message}",
  // Тосттор
  message_copied: "Билдирүү көчүрүлдү",
  failed_to_copy: "Билдирүү көчүрүлбөй калды",
  removed_from_group: "Сиз бул топтон чыгарылдыңыз",
  no_longer_admin: "Сиз бул топтун админи эмессиз",
  now_admin: "Сиз бул топтун админи болдуңуз",
  user_added_to_chat: "{username} колдонуuчусу чатка кошулду",
  user_not_found: "{username} колдонуuчусу бул чатта табылган жок",
  user_now_admin: "{username} эми админ болду",
  failed_to_make_admin: "Колдонуuчуну админ кылуu ишке ашпады",
  user_no_longer_admin: "{username} мындан ары админ эмес",
  failed_to_remove_admin: "Админ статусун алуu ишке ашпады",
  added_to_group: "Сиз {chatName} топко кошулдуңuз",
  member_added_to_group: "Бул топко жаңы мүчө кошулду",
  member_removed_from_group: "Мүчө бул топтон чыгарылды",
  admin_status_changed: "Бул топтогу админ статусу өзгөртүлдү",
  group_settings_updated: "Топтун жөндөөлөрү жаңыртылды",
  // Ката бет
  oops: "ой!",
  something_went_wrong: "бир нерсе туура эмес болду",
  try_again: "кайра аракет кылыңыз",
  error_apology:
    "кыялыбыз үчүн кечирим сурайбыз. баракты жаңылап же кийинчерээк аракет кылыңыз.",
  // Тил тандоо
  language: "тил",
  english: "англисче",
  spanish: "испанча",
  french: "французча",
  kyrgyz: "кыргызча",
  russian: "орусча",
  // Топ түзүү модалы
  group_name: "топтун аты",
  enter_group_name: "топтун атын жазыңыз",
  group_members: "топтун мүчөлөрү",
  enter_username_to_add: "кошуу үчүн колдонуuчунун атын жазыңыз",
  // Жаңы кошулган тексттер  message_deleted: "бул билдирүү өчүрүлдү",
  message_options: "билдирүү параметрлери",
  message_actions: "билдирүү аракеттери",
  // Системные сообщения
  system_joined_group: "{user} топко кошулду",
  system_left_group: "{user} топтон чыкты",
  system_created_group: "{user} топту түздү",
  system_added_user: "{adder} колдонuчуну кошту {added}",
  system_removed_user: "{remover} колдонuчуну чыгарды {removed}",
  search_chats: "чаттарды издөө...",
  no_chats_available: "жеткиликтүү чаттар жок",
  create_new_chat: "жаңы чат түзүү",
  create_group_chat: "топтук чат түзүү",
  type_username_and_press_enter:
    "колдонуuчунун атын жазыңыз жана enter басыңыз",
  add: "кошуу",
  create: "түзүү",
  enter_username: "колдонуuчунун атын жазыңыз",
  send_message: "билдирүү жөнөтүү",
  new_chat: "жаңы чат",
  one_member: "1 мүчө",
  members: "мүчөлөр",
  group_settings: "топтун жөндөөлөрү",
  group_description: "топтун сүрөттөлүшү",
  members_count: "{count} мүчө",
  user_made_admin: "{actor} {target} админ кылды",
  user_removed_admin: "{actor} {target} админ укуктарынан ажыратты",
  user_added_to_group: "{actor} {target} топко кошту",
  user_removed_from_group: "{actor} {target} топтон чыгарды",
  user_changed_group_settings: "{actor} топтун жөндөөлөрүн өзгөрттү",
  updated_group_settings: "{actor} топтун жөндөөлөрүн жаңыртты",
  two_members: "2 мүчө",
  three_members: "3 мүчө",
  you_were_removed_from_group: "Сиз {chatName} топтон чыгарылдыңыз",
  you_are_now_admin: "Сиз бул топтун админи болдуңуз",
  you_are_no_longer_admin: "Сиз бул топтун админи эмессиз",

  // Group management
  remove_from_group: "топтон чыгаруu",
  remove_admin_rights: "админ укуктарын алуu",
  make_admin: "админ кылуu",
  add_user: "колдонуuчуну кошуu",
  remove_user: "колдонуuчуну чыгаруu",
  are_you_sure: "сиз ишенимдүүсүзбү?",
  remove: "чыгаруu",
  confirm: "ырастоо",
  remove_admin_status_from: "{user} колдонуuчусунан админ статусун алуu",
  save_changes: "өзгөртүүлөрдү сактоu",

  // Forward message
  forward_message: "билдирүүнү бөлүшүү",
  select_chats_to_forward: "бөлүшүү үчүн чаттарды тандаңыз",
  no_chats_found: "чаттар табылган жок",
  selected_chats: "{count} чат тандалды",
  private_chat: "жеке чат",
  group_chat: "топтук чат",
  scroll_to_bottom: "ылдыйга түшүү",
  forwarded_message: "бөлүшүлгөн билдирүү",

  // Time format
  less_than_x_seconds_ago: "жаңы эле",
  half_a_minute_ago: "30 секунд мурун",
  x_minutes_ago: "{count} мүнөт мурун",
  x_minutes_ago_plural: "{count} мүнөт мурун",
  about_x_hours_ago: "{count} саат мурун тегерегинде",
  about_x_hours_ago_plural: "{count} саат мурун тегерегинде",
  x_days_ago: "{count} күн мурун",
  x_days_ago_plural: "{count} күн мурун",
  about_x_months_ago: "{count} ай мурун тегерегинде",
  about_x_months_ago_plural: "{count} ай мурун тегерегинде",
  x_years_ago: "{count} жыл мурун",
  x_years_ago_plural: "{count} жыл мурун",
  // Ката билдирүүлөрү
  error_ws_connection:
    "Реалдуу убакыт режиминдеги билдирүү кызматына туташуу ишке ашпады",
  error_load_chat: "Чатты жүктөө ишке ашпады",
  error_create_group: "Топту түзүү ишке ашпады",
  error_add_member: "Мүчөнү кошуу ишке ашпады",
  error_remove_member: "Мүчөнү чыгаруу ишке ашпады",
  error_leave_group: "Топтон чыгуу ишке ашпады",
  error_save_settings: "Жөндөөлөрдү сактоо ишке ашпады",
  error_send_message: "Билдирүүнү жөнөтүү ишке ашпады",
  error_edit_message: "Билдирүүнү түзөтүү ишке ашпады",
  error_delete_message: "Билдирүүнү өчүрүү ишке ашпады",
  error_forward_message: "Билдирүүлөрдү бөлүшүү ишке ашпады",
  // Билдирүү аталыштары
  toast_info: "Маалымат",
  toast_success: "Ийгиликтүү",
  toast_error: "Ката",

  // Cookie consent
  cookie_consent: "cookie жөндөөлөрү",
  cookie_consent_description:
    "бул сайт сиздин тажрыйбаңызды жакшыртуу үчүн cookie файлдарын колдонот. бул сайтты колдонуuну улантуu менен, сиз аутентификация, жөндөөлөр жана негизги функциялар үчүн cookie файлдарын колдонуuбузга макулдугуңuзду бересиз.",
  cookies_we_use: "биз колдонгон cookie файлдары",
  auth_cookies:
    "аутентификация cookie файлдары - сиздин киришиңизди коопсуз сактоо үчүн",
  preference_cookies:
    "жөндөөлөр cookie файлдары - сиздин тил жана тема тандооңузду эстеп калуu үчүн",
  functional_cookies:
    "функционалдык cookie файлдары - тиркеменин негизги функцияларын камсыздоо үчүн",
  select_your_language: "тилди тандаңыз",
  select_theme: "теманы тандаңыз",
  auto_detected_language: "браузериңизден автоматтык түрдө аныкталды",
  auto_detected_theme: "түзмөгүңүздөн автоматтык түрдө аныкталды",
  preferences_not_saved:
    "сиз системага киргенге чейин бул жөндөөлөр сакталбайт. биз сиздин түзмөгүңүздүн жөндөөлөрүн автоматтык түрдө аныктадык.",
  accept_and_continue: "кабыл алуu жана улантуu",
  not_available_now: "азыр жеткиликсиз",
  password_too_short: "сырсөз кеминде 8 символдон турушу керек",
  password_too_common: "сырсөз өтө жөнөкөй болбошу керек",
  password_entirely_numeric: "сырсөз жалаң сандардан турбашы керек",
  password_similar_to_personal:
    "сырсөз жеке маалыматка өтө окшош болбошу керек",
  passwords_dont_match: "сырсөздөр дал келбейт",
  username_taken: "бул колдонуuчу аты бош эмес",
  // Websocket status
  not_authenticated: "аутентификацияланган эмес",
  connection_failed: "туташуu катасы",
  could_not_connect_to_websocket: "вебсокетке байланыш түзүлбөй калды",
  websocket_connection_working: "вебсокет туташуuсу иштеп жатат",
  websocket_test_failed: "вебсокет тесттен өтпөй калды",
  websocket_test_error: "вебсокет тест катасы",
  member_actions: "мүчө аракеттери",
  owner: "ээси",
  please_log_in: "кирүүңүздү суранабыз",
  enter_group_description: "топтун сүрөттөмөсүн киргизиңиз",
  connecting: "туташуuда...",

  // Game translations
  play: "ойноо",
  tic_tac_toe: "крестики-ноликтер",
  waiting_for_opponent: "атаандаш күтүлүүдө...",
  invite_sent: "чакыруу жөнөтүлдү! атаандашыңыз кошулушун күтүңүз.",
  share_link_to_invite:
    "бул шилтемени досуңуз менен бөлүшүп, аны оюнга чакырыңыз.",
  your_turn: "сиздин жүрүшүңүз",
  opponent_turn: "{{username}} жүрүшү",
  you_won: "сиз жеңдиңиз!",
  you_lost: "сиз жеңилдиңиз!",
  game_draw: "тең чыктыңыздар!",
  play_again: "кайра ойноо",
  go_back: "артка",
  game_error: "оюн катасы",
  failed_to_initialize_game: "оюн баштала албады. кайра аракет кылыңыз.",
  authentication_error: "аутентификация катасы. кайра кирип, аракет кылыңыз.",
  authenticating: "аутентификацияланууда. күтө туруңуз...",
  please_wait: "күтө туруңуз",
  connecting_to_game: "оюн серверине кошулууда...",
  setting_up_game: "оюн даярдалууда...",
  connection_taking_long:
    "байланыш күткөндөн узак убакытка созулууда. бул уланса, баракты жаңылап көрүңүз.",
  connection_problem: "байланыш көйгөйү",
  authentication_failed_message:
    "аккаунтуңузду текшере албадык. кайра кириңиз.",
  connection_failed_message:
    "оюн серверине кошула албадык. байланышыңызды текшериңиз.",
  initialization_failed_message: "оюнду даярдай албадык. кайра аракет кылыңыз.",
  retry: "кайра аракет кылуу",
  copy_game_link: "оюн шилтемесин көчүрүү",
  return_to_chat: "маекке кайтуу",
  link_copied: "шилтеме көчүрүлдү",
  share_with_friends: "бирге ойноо үчүн достор менен бөлүшүңүз",
  copy_failed: "шилтемени көчүрүү мүмкүн болбоду",
  invite_to_play: "{{username}} колдонуuчусунун {{game}} оюнуна чакыруу",
  send_invitation: "чакыруу жөнөтүү",
  game_invitation_message: "{{username}} сизди {{game}} оюнуна чакырды",
  game_invitation_expired_message:
    "{{username}} колдонуuчусунун чакыруусу жарактуулуk мөөнөтү бүттү",
  join_game: "оюнга кошулуу",
  invitation_expired: "чакыруунун мөөнөтү бүттү",
  game_invitation_expired: "бул оюн чакыруусунун мөөнөтү бүттү",

  // New game sharing translations
  share_game: "оюн менен бөлүшүү",
  share_game_description: "крестики-ноликтер оюнуна достарыңызды чакырыңыз",
  share: "бөлүшүү",
  failed_to_share_game: "оюн чакыруусун жөнөтүү мүмкүн болбоду",
  game_invitation: "оюн чакыруусу",
  read: "окулду",
  sent: "жөнөтүлдү",
  sending: "жөнөтүлүүдө...",
  unknown_game_invitation: "белгисиз оюн чакыруусу",
};

export default kg;
