const ru = {
  // Навигация
  chats: "чаты",
  profile: "профиль",
  settings: "настройки",
  logout: "выйти",
  // Главная страница
  home_title: "используйте meowsenger для общения",
  home_subtitle: "красивый, быстрый и современный мессенджер",
  start_messaging: "начните общение",
  signing_up: "зарегистрируйтесь",
  already_have_account: "уже есть аккаунт?",
  // Страницы авторизации
  login: "войти",
  signup: "зарегистрироваться",
  username: "имя пользователя",
  password: "пароль",
  confirm_password: "подтвердите пароль",
  login_here: "войти здесь",
  signup_here: "зарегистрироваться здесь",
  choose_username: "выберите имя пользователя",
  create_password: "создайте пароль",
  confirm_your_password: "подтвердите ваш пароль",
  your_username: "ваше имя пользователя",
  your_password: "ваш пароль",
  // Профиль
  edit_profile: "редактировать профиль",
  save: "сохранить",
  cancel: "отмена",
  username_placeholder: "введите имя пользователя",
  description_placeholder: "введите краткую биографию",
  // Чат
  back: "назад",
  admin: "админ",
  tester: "тестер",
  no_messages: "сообщений пока нет. начните разговор!",
  this_message_was_deleted: "это сообщение было удалено",
  edited: "изменено",
  edited_short: "(изменено)",
  type_a_message: "введите сообщение...",
  send: "отправить",
  loading_conversation: "загрузка беседы...",
  conversation_not_found: "беседа не найдена или у вас нет доступа.",
  back_to_chats: "назад к чатам",
  replying_to_self: "отвечаете себе",
  reply_to_user: "ответ пользователю {user}",
  message_deleted: "это сообщение было удалено",
  message_options: "опции сообщения",
  message_actions: "действия с сообщением",
  search_chats: "поиск чатов...",
  no_chats_available: "нет доступных чатов",
  create_new_chat: "создать новый чат",
  create_group_chat: "создать групповой чат",
  type_username_and_press_enter: "введите имя пользователя и нажмите enter",
  add: "добавить",
  create: "создать",
  enter_username: "введите имя пользователя",
  send_message: "отправить сообщение",
  are_typing: "{count} человек(а) печатают...",
  editing_message: "редактируется сообщение: {message}",
  // Действия с сообщением
  copy: "копировать",
  reply: "ответить",
  forward: "переслать",
  edit: "редактировать",
  delete: "удалить",
  // Ввод сообщения
  edit_your_message: "редактируйте ваше сообщение...",
  reconnecting: "переподключение...",
  // Список сообщений
  load_older_messages: "загрузить старые сообщения",
  is_typing: "печатает...",
  replying_to: "ответ",
  // Тосты
  message_copied: "Сообщение скопировано в буфер обмена",
  failed_to_copy: "Не удалось скопировать сообщение",
  // Страница ошибки
  oops: "ой!",
  something_went_wrong: "что-то пошло не так",
  try_again: "попробовать снова",
  error_apology:
    "приносим извинения за неудобства. попробуйте обновить страницу или повторите попытку позже.",
  // Языковой селектор
  language: "язык",
  english: "английский",
  spanish: "испанский",
  french: "французский",
  kyrgyz: "кыргызский",
  russian: "русский",
  // Модальное окно создания чата
  group_name: "название группы",
  enter_group_name: "введите название группы",
  group_members: "участники группы",
  new_chat: "новый чат",
  members_count: "{count} участников",
  user_made_admin: "{actor} назначил(а) {target} админом",
  user_removed_admin: "{actor} снял(а) права админа у {target}",
  user_added_to_group: "{actor} добавил(а) {target} в группу",
  user_removed_from_group: "{actor} удалил(а) {target} из группы",
  user_changed_group_settings: "{actor} изменил(а) настройки группы",
  one_member: "1 участник",
  members: "участники",
  group_settings: "настройки группы",
  group_description: "описание группы",
};

export default ru;
