const en = {
  // Navigation
  chats: "chats",
  profile: "profile",
  settings: "settings",
  logout: "logout",
  // Home page
  home_title: "use meowsenger for messaging",
  home_subtitle: "beautiful, fast and modern messenger",
  start_messaging: "start messaging by",
  signing_up: "signing up",
  already_have_account: "already have an account?",
  // Auth pages
  login: "login",
  signup: "sign up",
  username: "username",
  password: "password",
  confirm_password: "confirm password",
  login_here: "login here",
  signup_here: "sign up here",
  choose_username: "choose a username",
  create_password: "create a password",
  confirm_your_password: "confirm your password",
  your_username: "your username",
  your_password: "your password",
  // Profile page
  edit_profile: "edit profile",
  save: "save",
  cancel: "cancel",
  username_placeholder: "enter username",
  description_placeholder: "enter a short bio",
  // Chat widget
  back: "back",
  admin: "admin",
  tester: "tester",
  no_messages: "no messages yet. start the conversation!",
  this_message_was_deleted: "this message was deleted",
  edited: "edited",
  type_a_message: "type a message...",
  send: "send",
  loading_conversation: "loading conversation...",
  conversation_not_found: "conversation not found or you don't have access.",
  back_to_chats: "back to chats",
  // Message actions
  copy: "copy",
  reply: "reply",
  forward: "forward",
  edit: "edit",
  delete: "delete",
  // Message input
  edit_your_message: "edit your message...",
  reconnecting: "reconnecting...",
  // Message list
  load_older_messages: "load older messages",
  is_typing: "is typing...",
  are_typing: "{count} people are typing...",
  replying_to: "replying to",
  replying_to_self: "replying to self",
  reply_to_user: "reply to {user}",
  editing_message: "editing message: {message}",
  // Toasts
  message_copied: "Message copied to clipboard",
  failed_to_copy: "Failed to copy message",
  // Error page
  oops: "oops!",
  something_went_wrong: "something went wrong",
  try_again: "try again",
  error_apology:
    "we apologize for the inconvenience. please try refreshing the page or try again later.",
  // Language selector
  language: "language",
  english: "english",
  spanish: "spanish",
  french: "french",
  kyrgyz: "kyrgyz",
  russian: "russian",
  // Create chat modal
  group_name: "group name",
  enter_group_name: "enter group name",
  group_members: "group members",
  // Message system and reply labels
  message_deleted: "this message was deleted",
  edited_short: "(edited)",
  // Message menu
  message_options: "message options",
  message_actions: "message actions",
  // Message list additions
  search_chats: "search chats...",
  no_chats_available: "no chats available",
  create_new_chat: "create new chat",
  create_group_chat: "create group chat",
  type_username_and_press_enter: "type username and press enter",
  add: "add",
  create: "create",
  enter_username: "enter username",
  send_message: "send message",
  new_chat: "new chat",
  one_member: "1 member",
  members: "members",
  group_settings: "group settings",
  group_description: "group description",
  members_count: "{count} members",
  user_made_admin: "{actor} made {target} an admin",
  user_removed_admin: "{actor} removed admin rights from {target}",
  user_added_to_group: "{actor} added {target} to the group",
  user_removed_from_group: "{actor} removed {target} from the group",
  user_changed_group_settings: "{actor} changed group settings",
  you_were_removed_from_group: "You were removed from {chatName}",
  you_are_now_admin: "You are now an admin in this group",
  you_are_no_longer_admin: "You are no longer an admin in this group",
  two_members: "2 members",
  three_members: "3 members",
};

export default en;
