const kg = {
  // Навигация
  chats: "чаттар",
  profile: "профиль",
  settings: "жөндөөлөр",
  logout: "чыгуу",
  // Башкы бет
  home_title: "meowsenger менен баарлашуу",
  home_subtitle: "кооз, тез жана заманбап мессенджер",
  start_messaging: "баарлашууну баштаңыз",
  signing_up: "катталыңыз",
  already_have_account: "аккаунтуңуз барбы?",
  // Авторизация беттери
  login: "кируу",
  signup: "катталуу",
  username: "колдонуучу аты",
  password: "сырсөз",
  confirm_password: "сырсөздү ырастаңыз",
  login_here: "ушул жерден кириңиз",
  signup_here: "ушул жерден катталыңыз",
  choose_username: "колдонуучу атын тандаңыз",
  create_password: "сырсөз түзүңүз",
  confirm_your_password: "сырсөздү ырастаңыз",
  your_username: "сиздин колдонуучу атыңыз",
  your_password: "сиздин сырсөзүңүз",
  // Профиль
  edit_profile: "профилди түзөтүү",
  save: "сактоо",
  cancel: "жокко чыгаруу",
  username_placeholder: "колдонуучу атын жазыңыз",
  description_placeholder: "кыскача био жазыңыз",
  // Чат
  back: "артка",
  admin: "админ",
  tester: "тестер",
  no_messages: "жазуулар жок. сүйлөшүүнү баштаңыз!",
  this_message_was_deleted: "бул билдирүү өчүрүлдү",
  edited: "өзгөртүлдү",
  edited_short: "(өзгөртүлдү)",
  type_a_message: "билдирүү жазыңыз...",
  send: "жөнөтүү",
  loading_conversation: "сүйлөшүү жүктөлүүдө...",
  conversation_not_found: "сүйлөшүү табылган жок же сизде мүмкүнчүлүк жок.",
  back_to_chats: "чаттарга кайтуу",
  // Билдирүү аракеттери
  copy: "которуу",
  reply: "жооп берүү",
  forward: "бөлүшүү",
  edit: "түзөтүү",
  delete: "өчүрүү",
  // Билдирүү жазуу
  edit_your_message: "билдирүүнү түзөтүңүз...",
  reconnecting: "кайра туташууда...",
  // Билдирүү тизмеси
  load_older_messages: "эски билдирүүлөрдү жүктөө",
  is_typing: "жазып жатат...",
  are_typing: "{count} колдонуучу жазып жатат...",
  replying_to: "жооп берүү",
  replying_to_self: "өзүңүзгө жооп берип жатасыз",
  reply_to_user: "{user} колдонуучуга жооп берүү",
  editing_message: "билдирүү түзөтүлүүдө: {message}",
  // Тосттор
  message_copied: "Билдирүү көчүрүлдү",
  failed_to_copy: "Билдирүү көчүрүлбөй калды",
  // Ката бет
  oops: "ой!",
  something_went_wrong: "бир нерсе туура эмес болду",
  try_again: "кайра аракет кылыңыз",
  error_apology:
    "кыялыбыз үчүн кечирим сурайбыз. баракты жаңылап же кийинчерээк аракет кылыңыз.",
  // Тил тандоо
  language: "тил",
  english: "англисче",
  spanish: "испанча",
  french: "французча",
  kyrgyz: "кыргызча",
  russian: "орусча",
  // Топ түзүү модалы
  group_name: "топтун аты",
  enter_group_name: "топтун атын жазыңыз",
  group_members: "топтун мүчөлөрү",
  // Жаңы кошулган тексттер
  message_deleted: "бул билдирүү өчүрүлдү",
  message_options: "билдирүү параметрлери",
  message_actions: "билдирүү аракеттери",
  search_chats: "чаттарды издөө...",
  no_chats_available: "жеткиликтүү чаттар жок",
  create_new_chat: "жаңы чат түзүү",
  create_group_chat: "топтук чат түзүү",
  type_username_and_press_enter:
    "колдонуучунун атын жазыңыз жана enter басыңыз",
  add: "кошуу",
  create: "түзүү",
  enter_username: "колдонуучунун атын жазыңыз",
  send_message: "билдирүү жөнөтүү",
  new_chat: "жаңы чат",
  one_member: "1 мүчө",
  members: "мүчөлөр",
  group_settings: "топтун жөндөөлөрү",
  group_description: "топтун сүрөттөлүшү",
  members_count: "{count} мүчө",
  user_made_admin: "{actor} {target} админ кылды",
  user_removed_admin: "{actor} {target} админ укуктарынан ажыратты",
  user_added_to_group: "{actor} {target} топко кошту",
  user_removed_from_group: "{actor} {target} топтон чыгарды",
  user_changed_group_settings: "{actor} топтун жөндөөлөрүн өзгөрттү",
  two_members: "2 мүчө",
  three_members: "3 мүчө",
};

export default kg;
