const en = {
  // Navigation
  chats: "chats",
  profile: "profile",
  settings: "settings",
  logout: "logout",
  games: "Games",
  // Home page
  home_title: "use meowsenger for messaging",
  home_subtitle: "beautiful, fast and modern messenger",
  start_messaging: "start messaging by",
  signing_up: "signing up",
  already_have_account: "already have an account?",
  // Auth pages
  login: "login",
  signup: "sign up",
  username: "username",
  password: "password",
  confirm_password: "confirm password",
  login_here: "login here",
  signup_here: "sign up here",
  choose_username: "choose a username",
  create_password: "create a password",
  confirm_your_password: "confirm your password",
  your_username: "your username",
  your_password: "your password",
  login_to_meowsenger: "login to meowsenger",
  welcome_back_enter_credentials: "welcome back! enter your credentials",
  log_in: "log in",
  dont_have_account: "don't have an account?",
  create_account_to_start_messaging: "create an account to start messaging",
  creating_account: "creating account...",
  logging_in: "logging in...",
  // Auth error messages
  error_password_too_short: "password must be at least 8 characters long",
  error_password_too_common: "password can't be a commonly used password",
  error_password_entirely_numeric: "password cannot be entirely numeric",
  error_password_similar_to_personal:
    "password can't be too similar to your personal information",
  error_passwords_dont_match: "passwords don't match",
  error_username_taken: "username is already taken",
  error_invalid_credentials: "invalid username or password",
  error_authentication_failed: "authentication failed, please try again",
  error_registration_failed:
    "registration failed, please check your information and try again",
  error_server: "server error, please try again later",
  password_too_short: "password must be at least 8 characters long",
  password_too_common: "password can't be a commonly used password",
  password_entirely_numeric: "password cannot be entirely numeric",
  password_similar_to_personal:
    "password can't be too similar to your personal information",
  passwords_dont_match: "passwords don't match",
  username_taken: "username is already taken",
  // Profile page
  edit_profile: "edit profile",
  save: "save",
  cancel: "cancel",
  username_placeholder: "enter username",
  description_placeholder: "enter a short bio",
  // Chat widget
  back: "back",
  admin: "admin",
  tester: "tester",
  no_messages: "no messages yet. start the conversation!",
  no_messages_short: "no messages",
  this_message_was_deleted: "this message was deleted",
  edited: "edited",
  type_a_message: "type a message...",
  send: "send",
  loading_conversation: "loading conversation...",
  conversation_not_found: "conversation not found or you don't have access.",
  back_to_chats: "back to chats",
  // Message actions
  copy: "copy",
  reply: "reply",
  forward: "forward",
  edit: "edit",
  delete: "delete",
  // Message input
  edit_your_message: "edit your message...",
  reconnecting: "reconnecting...",
  connected: "connected",
  disconnected: "disconnected",
  // Message list
  load_older_messages: "load older messages",
  is_typing: "is typing...",
  are_typing: "{count} people are typing...",
  replying_to: "replying to",
  replying_to_self: "replying to self",
  reply_to_user: "reply to {user}",
  editing_message: "editing message: {message}",
  // Toasts
  message_copied: "Message copied to clipboard",
  failed_to_copy: "Failed to copy message",
  removed_from_group: "You have been removed from this group",
  no_longer_admin: "You are no longer an admin in this group",
  now_admin: "You are now an admin in this group",
  user_added_to_chat: "Added {username} to the chat",
  user_not_found: "User {username} not found in this chat",
  user_now_admin: "{username} is now an admin",
  failed_to_make_admin: "Failed to make user an admin",
  user_no_longer_admin: "{username} is no longer an admin",
  failed_to_remove_admin: "Failed to remove admin status",
  added_to_group: "You were added to {chatName}",
  member_added_to_group: "A new member was added to this group",
  member_removed_from_group: "A member was removed from this group",
  admin_status_changed: "Admin status changed in this group",
  group_settings_updated: "Group settings were updated",
  // Error messages
  error_ws_connection: "Failed to connect to real-time messaging service",
  error_load_chat: "Failed to load chat",
  error_create_group: "Failed to create group",
  error_add_member: "Failed to add member",
  error_remove_member: "Failed to remove member",
  error_leave_group: "Failed to leave group",
  error_save_settings: "Failed to save settings",
  error_send_message: "Failed to send message",
  error_edit_message: "Failed to edit message",
  error_delete_message: "Failed to delete message",
  error_forward_message: "Failed to forward messages",
  // Error page
  oops: "oops!",
  something_went_wrong: "something went wrong",
  try_again: "try again",
  error_apology:
    "we apologize for the inconvenience. please try refreshing the page or try again later.",
  // Language selector
  language: "language",
  english: "english",
  spanish: "spanish",
  french: "french",
  kyrgyz: "kyrgyz",
  russian: "russian",
  // Create chat modal
  group_name: "group name",
  enter_group_name: "enter group name",
  group_members: "group members",
  enter_username_to_add: "enter username to add",
  // Message system and reply labels
  message_deleted: "this message was deleted",
  edited_short: "(edited)",
  forwarded_message: "forwarded message",
  // Message menu
  message_options: "message options",
  message_actions: "message actions",
  // System messages
  system_joined_group: "{user} joined the group",
  system_left_group: "{user} left the group",
  system_created_group: "{user} created the group",
  system_added_user: "{adder} added {added}",
  system_removed_user: "{remover} removed {removed}",
  user_made_admin: "{actor} made {target} an admin",
  user_removed_admin: "{actor} removed admin rights from {target}",
  user_added_to_group: "{actor} added {target} to the group",
  user_removed_from_group: "{actor} removed {target} from the group",
  user_changed_group_settings: "{actor} changed group settings",
  updated_group_settings: "{actor} updated group settings",
  // Message list additions
  search_chats: "search chats...",
  no_chats_available: "no chats available",
  create_new_chat: "create new chat",
  create_group_chat: "create group chat",
  type_username_and_press_enter: "type username and press enter",
  add: "add",
  create: "create",
  enter_username: "enter username",
  send_message: "send message",
  new_chat: "new chat",
  one_member: "1 member",
  members: "members",
  group_settings: "group settings",
  group_description: "group description",
  members_count: "{count} members",
  you_were_removed_from_group: "You were removed from {chatName}",
  you_are_now_admin: "You are now an admin in this group",
  you_are_no_longer_admin: "You are no longer an admin in this group",
  two_members: "2 members",
  three_members: "3 members",

  // Group management
  remove_from_group: "remove from group",
  remove_admin_rights: "remove admin rights",
  make_admin: "make admin",
  add_user: "add user",
  remove_user: "remove user",
  are_you_sure: "are you sure?",
  remove: "remove",
  confirm: "confirm",
  remove_admin_status_from: "remove admin status from {user}",
  save_changes: "save changes",

  // Forward message
  forward_message: "forward message",
  select_chats_to_forward: "select chats to forward to",
  no_chats_found: "no chats found",
  selected_chats: "{count} chats selected",
  private_chat: "private chat",
  group_chat: "group chat",
  scroll_to_bottom: "scroll to bottom",

  // Time format
  less_than_x_seconds_ago: "just now",
  half_a_minute_ago: "30 seconds ago",
  x_minutes_ago: "{count} minute ago",
  x_minutes_ago_plural: "{count} minutes ago",
  about_x_hours_ago: "about {count} hour ago",
  about_x_hours_ago_plural: "about {count} hours ago",
  x_days_ago: "{count} day ago",
  x_days_ago_plural: "{count} days ago",
  about_x_months_ago: "about {count} month ago",
  about_x_months_ago_plural: "about {count} months ago",
  x_years_ago: "{count} year ago",
  x_years_ago_plural: "{count} years ago",
  // Toast titles
  toast_info: "Info",
  toast_success: "Success",
  toast_error: "Error",

  // Cookie consent
  cookie_consent: "cookie settings",
  cookie_consent_description:
    "this site uses cookies to improve your experience. by continuing to use this site, you agree to our use of cookies for authentication, preferences, and essential functionality.",
  cookies_we_use: "cookies we use",
  auth_cookies: "authentication cookies - to keep you logged in securely",
  preference_cookies:
    "preference cookies - to remember your language and theme",
  functional_cookies:
    "functional cookies - to provide core features of the app",
  select_your_language: "select your language",
  select_theme: "select theme",
  auto_detected_language: "automatically detected from your browser",
  auto_detected_theme: "automatically detected from your device",
  preferences_not_saved:
    "these preferences will not be saved until you log in. we've automatically detected your device settings.",
  accept_and_continue: "accept and continue",
  not_available_now: "not available now",
  // Websocket status
  not_authenticated: "not authenticated",
  connection_failed: "connection failed",
  could_not_connect_to_websocket: "could not connect to websocket",
  websocket_connection_working: "websocket connection working",
  websocket_test_failed: "websocket test failed",
  websocket_test_error: "websocket test error",
  member_actions: "member actions",
  owner: "owner",
  please_log_in: "please log in",
  enter_group_description: "enter group description",
  connecting: "connecting...",

  // Game translations
  tic_tac_toe: "tic tac toe",
  loading: "loading",
  creating_game: "creating game",
  joining_game: "joining game",
  authenticating: "authenticating",
  connection_taking_long: "connection is taking longer than expected",
  setting_up_game: "setting up the game environment",
  preparing_game: "preparing the game",
  waiting_for_opponent: "waiting for opponent",
  your_turn: "your turn",
  opponent_turn: "{username}'s turn",
  game_error: "game error",
  failed_to_initialize_game: "failed to initialize the game",
  game_draw: "it's a draw!",
  you_won: "you won!",
  you_lost: "you lost!",
  play_again: "play again",
  go_back: "go back",
  invite_to_play: "invite {username} to play {game}",
  send_invitation: "send invitation",
  copy_game_link: "copy game link",
  share_with_friends: "share with friends",
  share_game: "share game",
  return_to_chat: "return to chat",
  share_game_description: "invite friends to play by sharing this game",
  link_copied: "link copied to clipboard",
  invitation_sent: "game invitation sent",
  game_invitation_message: "{username} invited you to play {game}",
  game_invitation_expired_message:
    "invitation from {username} to play {game} has expired",
  join_game: "join game",
  invitation_expired: "invitation expired",
  please_wait: "please wait",
  connecting_to_game: "connecting to game",
  failed_to_share_game: "failed to share game",
  connection_problem: "connection problem",
  authentication_failed_message:
    "failed to authenticate with the game server. please try again.",
  connection_failed_message:
    "failed to connect to the game server. please check your internet connection.",
  initialization_failed_message:
    "failed to initialize the game. please try again later.",
  retry: "retry",
};

export default en;
