const ru = {
  // Навигация
  chats: "чаты",
  profile: "профиль",
  settings: "настройки",
  logout: "выйти",
  games: "игры",
  // Главная страница
  home_title: "используйте meowsenger для общения",
  home_subtitle: "красивый, быстрый и современный мессенджер",
  start_messaging: "начните общение",
  signing_up: "зарегистрируйтесь",
  already_have_account: "уже есть аккаунт?",
  // Страницы авторизации
  login: "войти",
  signup: "регистрация",
  username: "имя пользователя",
  password: "пароль",
  confirm_password: "подтвердите пароль",
  login_here: "войти здесь",
  signup_here: "зарегистрироваться здесь",
  choose_username: "выберите имя пользователя",
  create_password: "создайте пароль",
  confirm_your_password: "подтвердите ваш пароль",
  your_username: "ваше имя пользователя",
  your_password: "ваш пароль",
  login_to_meowsenger: "вход в meowsenger",
  welcome_back_enter_credentials: "с возвращением! введите свои данные",
  log_in: "войти",
  dont_have_account: "нет аккаунта?",
  create_account_to_start_messaging: "создайте аккаунт чтобы начать общение",
  creating_account: "создание аккаунта...",
  logging_in: "вход в систему...",
  // Сообщения об ошибках авторизации
  error_password_too_short: "пароль должен быть не менее 8 символов",
  error_password_too_common: "пароль не должен быть слишком распространенным",
  error_password_entirely_numeric: "пароль не может состоять только из цифр",
  error_password_similar_to_personal:
    "пароль не должен быть похож на личную информацию",
  error_passwords_dont_match: "пароли не совпадают",
  error_username_taken: "это имя пользователя уже занято",
  error_invalid_credentials: "неверное имя пользователя или пароль",
  error_authentication_failed: "ошибка аутентификации, попробуйте еще раз",
  error_registration_failed:
    "ошибка регистрации, проверьте введенные данные и попробуйте снова",
  error_server: "ошибка сервера, пожалуйста, попробуйте позже",
  // Профиль
  edit_profile: "редактировать профиль",
  save: "сохранить",
  cancel: "отмена",
  username_placeholder: "введите имя пользователя",
  description_placeholder: "введите краткую биографию", // Чат
  back: "назад",
  admin: "админ",
  tester: "тестер",
  no_messages: "сообщений пока нет. начните разговор!",
  no_messages_short: "сообщений нет",
  this_message_was_deleted: "это сообщение было удалено",
  edited: "изменено",
  edited_short: "(изменено)",
  type_a_message: "введите сообщение...",
  send: "отправить",
  loading_conversation: "загрузка чата...",
  conversation_not_found: "чат не найден или у вас нет доступа.",
  back_to_chats: "назад к чатам",
  replying_to_self: "отвечаете себе",
  reply_to_user: "ответ пользователю {user}",
  message_deleted: "это сообщение было удалено",
  message_options: "опции сообщения",
  message_actions: "действия с сообщением",
  // Системные сообщения
  system_joined_group: "{user} присоединился к группе",
  system_left_group: "{user} покинул группу",
  system_created_group: "{user} создал группу",
  system_added_user: "{adder} добавил(а) {added}",
  system_removed_user: "{remover} удалил(а) {removed}",
  search_chats: "поиск чатов...",
  no_chats_available: "нет доступных чатов",
  create_new_chat: "создать новый чат",
  create_group_chat: "создать групповой чат",
  type_username_and_press_enter: "введите имя пользователя и нажмите enter",
  add: "добавить",
  create: "создать",
  enter_username: "введите имя пользователя",
  send_message: "отправить сообщение",
  are_typing: "{count} человек(а) печатают...",
  editing_message: "редактируется сообщение: {message}",
  // Действия с сообщением
  copy: "копировать",
  reply: "ответить",
  forward: "переслать",
  edit: "редактировать",
  delete: "удалить",
  // Ввод сообщения
  edit_your_message: "редактируйте ваше сообщение...",
  reconnecting: "переподключение...",
  // Список сообщений
  load_older_messages: "загрузить старые сообщения",
  is_typing: "печатает...",
  replying_to: "ответ",
  // Заголовки уведомлений
  toast_info: "Информация",
  toast_success: "Успешно",
  toast_error: "Ошибка",
  // Тосты
  message_copied: "Сообщение скопировано в буфер обмена",
  failed_to_copy: "Не удалось скопировать сообщение",
  removed_from_group: "Вы были удалены из этой группы",
  no_longer_admin: "Вы больше не администратор в этой группе",
  now_admin: "Вы теперь администратор в этой группе",
  user_added_to_chat: "Пользователь {username} добавлен в чат",
  user_not_found: "Пользователь {username} не найден в этом чате",
  user_now_admin: "{username} теперь администратор",
  failed_to_make_admin: "Не удалось назначить пользователя администратором",
  user_no_longer_admin: "{username} больше не администратор",
  failed_to_remove_admin: "Не удалось снять статус администратора",
  added_to_group: "Вы были добавлены в группу {chatName}",
  member_added_to_group: "В эту группу был добавлен новый участник",
  member_removed_from_group: "Участник был удален из этой группы",
  admin_status_changed: "Статус администратора изменен в этой группе",
  group_settings_updated: "Настройки группы были обновлены",
  // Сообщения об ошибках
  error_ws_connection:
    "Не удалось подключиться к сервису сообщений в реальном времени",
  error_load_chat: "Не удалось загрузить чат",
  error_create_group: "Не удалось создать группу",
  error_add_member: "Не удалось добавить участника",
  error_remove_member: "Не удалось удалить участника",
  error_leave_group: "Не удалось покинуть группу",
  error_save_settings: "Не удалось сохранить настройки",
  error_send_message: "Не удалось отправить сообщение",
  error_edit_message: "Не удалось изменить сообщение",
  error_delete_message: "Не удалось удалить сообщение",
  error_forward_message: "Не удалось переслать сообщения",
  // Страница ошибки
  oops: "ой!",
  something_went_wrong: "что-то пошло не так",
  try_again: "попробовать снова",
  error_apology:
    "приносим извинения за неудобства. попробуйте обновить страницу или повторите попытку позже.", // Языковой селектор
  language: "язык",
  english: "английский",
  spanish: "испанский",
  french: "французский",
  kyrgyz: "кыргызский",
  russian: "русский",
  // Модальное окно создания чата
  group_name: "название группы",
  enter_group_name: "введите название группы",
  group_members: "участники группы",
  new_chat: "новый чат",
  members_count: "{count} участников",
  user_made_admin: "{actor} назначил(а) {target} админом",
  user_removed_admin: "{actor} снял(а) права админа у {target}",
  user_added_to_group: "{actor} добавил(а) {target} в группу",
  user_removed_from_group: "{actor} удалил(а) {target} из группы",
  user_changed_group_settings: "{actor} изменил(а) настройки группы",
  updated_group_settings: "{actor} обновил(а) настройки группы",
  one_member: "1 участник",
  members: "участники",
  group_settings: "настройки группы",
  group_description: "описание группы",
  you_were_removed_from_group: "Вы были удалены из {chatName}",
  you_are_now_admin: "Вы теперь администратор в этой группе",
  you_are_no_longer_admin: "Вы больше не администратор в этой группе",
  two_members: "2 участника",
  three_members: "3 участника",

  // Group management
  remove_from_group: "удалить из группы",
  remove_admin_rights: "лишить прав администратора",
  make_admin: "назначить администратором",
  add_user: "добавить пользователя",
  remove_user: "удалить пользователя",
  are_you_sure: "вы уверены?",
  remove: "удалить",
  confirm: "подтвердить",
  remove_admin_status_from: "лишить {user} статуса администратора",
  save_changes: "сохранить изменения",

  // Forward message
  forward_message: "переслать сообщение",
  select_chats_to_forward: "выберите чаты для пересылки",
  no_chats_found: "чаты не найдены",
  selected_chats: "выбрано чатов: {count}",
  private_chat: "личный чат",
  group_chat: "групповой чат",
  scroll_to_bottom: "прокрутить вниз",
  forwarded_message: "пересланное сообщение",

  // Time format
  less_than_x_seconds_ago: "только что",
  half_a_minute_ago: "30 секунд назад",
  x_minutes_ago: "{count} минуту назад",
  x_minutes_ago_plural: "{count} минут назад",
  about_x_hours_ago: "около {count} часа назад",
  about_x_hours_ago_plural: "около {count} часов назад",
  x_days_ago: "{count} день назад",
  x_days_ago_plural: "{count} дней назад",
  about_x_months_ago: "около {count} месяца назад",
  about_x_months_ago_plural: "около {count} месяцев назад",
  x_years_ago: "{count} год назад",
  x_years_ago_plural: "{count} лет назад",

  // Cookie consent
  cookie_consent: "настройки файлов cookie",
  cookie_consent_description:
    "этот сайт использует файлы cookie для улучшения вашего опыта. продолжая использовать этот сайт, вы соглашаетесь с нашим использованием файлов cookie для аутентификации, предпочтений и основных функций.",
  cookies_we_use: "файлы cookie, которые мы используем",
  auth_cookies:
    "файлы аутентификации — для сохранения безопасности вашего входа",
  preference_cookies:
    "файлы предпочтений — для запоминания вашего языка и темы",
  functional_cookies:
    "функциональные файлы cookie — для обеспечения основных функций приложения",
  select_your_language: "выберите язык",
  select_theme: "выберите тему",
  auto_detected_language: "автоматически определен из вашего браузера",
  auto_detected_theme: "автоматически определен из вашего устройства",
  preferences_not_saved:
    "эти настройки не будут сохранены, пока вы не войдете в систему. мы автоматически определили настройки вашего устройства.",
  accept_and_continue: "принять и продолжить",
  not_available_now: "сейчас недоступно",
  password_too_short: "пароль должен быть не менее 8 символов",
  password_too_common: "пароль не должен быть слишком распространенным",
  password_entirely_numeric: "пароль не может состоять только из цифр",
  password_similar_to_personal:
    "пароль не должен быть похож на личную информацию",
  passwords_dont_match: "пароли не совпадают",
  username_taken: "это имя пользователя уже занято",
};

export default ru;
