# Generated by Django 5.2 on 2025-04-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0002_remove_user_avatar_remove_user_bio_user_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='1758d049176d949ddbf8472b3e2c3009', max_length=64),
        ),
    ]
