# Generated by Django 5.2 on 2025-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0003_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='45576dd636b8ac4ef26e4a03ac32f3a1', max_length=64),
        ),
    ]
