# Generated by Django 5.2 on 2025-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0006_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='b794c732467f585f7b7893b5eba74e1e', max_length=64),
        ),
    ]
