# Generated by Django 5.2 on 2025-04-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0009_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='1037b9b32eb0ad19fe7379fbfb2a4ce7', max_length=64),
        ),
    ]
