# Generated by Django 5.2 on 2025-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0010_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='b22ef9685b5b9b78c4253b638712aead', max_length=64),
        ),
    ]
