# Generated by Django 5.2 on 2025-04-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0011_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='760073c3844f4b241b11c9f42014f990', max_length=64),
        ),
    ]
