# Generated by Django 5.2 on 2025-04-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0012_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='a4150306e252a846dcd070b9df9d3c23', max_length=64),
        ),
    ]
