# Generated by Django 5.2 on 2025-04-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0013_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='cbda53c4b22ae768fc632815b6abc5e1', max_length=64),
        ),
    ]
