# Generated by Django 5.2 on 2025-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0018_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='f40eba473b317e68cd126c6e04bbcae2', max_length=64),
        ),
    ]
