# Generated by Django 5.2 on 2025-04-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0019_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='4dc336f99e988de8f1fe712eea09d74e', max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notify',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='update',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
