# Generated by Django 5.2 on 2025-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0020_alter_chat_id_alter_chat_secret_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='b457f9bde45d151c4096f328b93a53c1', max_length=64),
        ),
    ]
