# Generated by Django 5.2 on 2025-04-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0021_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='76d926cc9a32ebd4811173bf2a09043c', max_length=64),
        ),
    ]
