# Generated by Django 5.2 on 2025-04-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0022_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='70a0a9468195a530c335e20e3579c68d', max_length=64),
        ),
    ]
