# Generated by Django 5.2 on 2025-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0023_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='6518669fbd942a7ca1decbf7c6ae5235', max_length=64),
        ),
    ]
