# Generated by Django 5.2 on 2025-04-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0024_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='3dfe1c32aad18c6b16743bac872471eb', max_length=64),
        ),
    ]
