# Generated by Django 5.2 on 2025-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0025_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='86afd6d735d496107185b1d06e4b0e10', max_length=64),
        ),
    ]
