# Generated by Django 5.2 on 2025-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0026_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='000445fd9710a696fe324cb786f00993', max_length=64),
        ),
    ]
