# Generated by Django 5.2 on 2025-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0027_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='de08718e523d73b27b9e480e564ad949', max_length=64),
        ),
    ]
