# Generated by Django 5.2 on 2025-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0028_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='35913cf26a36af03cc84c210fd522cb9', max_length=64),
        ),
    ]
