# Generated by Django 5.2 on 2025-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0029_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='5659d946706c0a52d2e3485d988df584', max_length=64),
        ),
    ]
