# Generated by Django 5.2 on 2025-04-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0030_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='b022e5ea4f6ef3892c1e2c32b4b12931', max_length=64),
        ),
    ]
