# Generated by Django 5.2 on 2025-04-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0031_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='ea91376d3c486db5ee0d8468490e4bc1', max_length=64),
        ),
    ]
