# Generated by Django 5.2 on 2025-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0033_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='eeed74be94dd82d69c846ebbaf4ef781', max_length=64),
        ),
    ]
