# Generated by Django 5.2 on 2025-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0034_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='dec4b368a1d289439ed13d4a258c4695', max_length=64),
        ),
    ]
