# Generated by Django 5.2 on 2025-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0035_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='e9233a7d0db9824e21d23dd0cd133b73', max_length=64),
        ),
    ]
