# Generated by Django 5.2 on 2025-04-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0036_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='02b4b9514b14e9eda3f0e2e4561b01dc', max_length=64),
        ),
    ]
