# Generated by Django 5.2 on 2025-04-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0037_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='5158b58e7dd73d54e44a248412b76e96', max_length=64),
        ),
    ]
