# Generated by Django 5.2 on 2025-04-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0038_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='37384a632e32ee39689a3dc6700e04b0', max_length=64),
        ),
    ]
