# Generated by Django 5.2 on 2025-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0039_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='25898b058281e3ccd8f827e8377a2c9f', max_length=64),
        ),
    ]
