# Generated by Django 5.2 on 2025-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0040_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='d8a82cae52bdb59b3973bfa915b806c4', max_length=64),
        ),
    ]
