# Generated by Django 5.2 on 2025-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0041_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='6d952e984692a9d8ce42f6d37d2b1be2', max_length=64),
        ),
    ]
