# Generated by Django 5.2 on 2025-04-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0042_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='5a3a0622adb2c32c19eb4e9dad20f504', max_length=64),
        ),
    ]
