# Generated by Django 5.2 on 2025-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0043_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='7402820bdd2d2162d021336b0821c993', max_length=64),
        ),
    ]
