# Generated by Django 5.2 on 2025-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0044_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='0990947b5ce1061bbbfd0da27cc3770c', max_length=64),
        ),
    ]
