# Generated by Django 5.2 on 2025-04-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0045_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='77c72d26c4accbcc4cf4b38b9a515695', max_length=64),
        ),
    ]
