# Generated by Django 5.2 on 2025-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0047_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='f92cc9dd052839a3c758eecbd93de78d', max_length=64),
        ),
    ]
