# Generated by Django 5.2 on 2025-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0048_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='1232c3464604b01ae1fdda7363d0841c', max_length=64),
        ),
    ]
