# Generated by Django 5.2 on 2025-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0049_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='bfd838b2fb1a87e156e94e64ef1995f8', max_length=64),
        ),
    ]
