# Generated by Django 5.2 on 2025-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0050_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='baa037df843935574d2cfba8e4f70253', max_length=64),
        ),
    ]
