# Generated by Django 5.2 on 2025-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0051_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='febad61b2700a0b655e7d9b2b64c401b', max_length=64),
        ),
    ]
