# Generated by Django 5.2 on 2025-05-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0052_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='1714f0f75cf5dbd5bd3cb3a2d2b6e0f0', max_length=64),
        ),
    ]
