# Generated by Django 5.2 on 2025-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0053_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='2cba36be5e97cb7f0205733bd8c53d33', max_length=64),
        ),
    ]
