# Generated by Django 5.2 on 2025-05-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0054_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='21ec277e542b21ac2e0e064d205a0ed8', max_length=64),
        ),
    ]
