# Generated by Django 5.2 on 2025-05-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0055_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='6d0519290a392549cd2f34609a2ea83c', max_length=64),
        ),
    ]
