# Generated by Django 5.2 on 2025-05-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0056_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='e66d1973268dd0196123f9d19ed17f53', max_length=64),
        ),
    ]
