# Generated by Django 5.2 on 2025-05-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0057_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='d958396e597396129ef37c89aa63cd89', max_length=64),
        ),
    ]
