# Generated by Django 5.2 on 2025-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0058_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='e8c929d23dca77e5d66803161a051c35', max_length=64),
        ),
    ]
