# Generated by Django 5.2 on 2025-05-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0059_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='ffc308ccf06682298fe8f1d4f2e065a1', max_length=64),
        ),
    ]
