# Generated by Django 5.2 on 2025-05-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0060_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='abdb38c919d4f22a2074f129f1aa36af', max_length=64),
        ),
    ]
