# Generated by Django 5.2 on 2025-05-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0061_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='33e14629ae40629dc28209977e277c3f', max_length=64),
        ),
    ]
