# Generated by Django 5.2 on 2025-05-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0062_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='335443b2ccef4faa033ec6b89712d734', max_length=64),
        ),
    ]
