# Generated by Django 5.2 on 2025-05-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0063_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='0331a585c6388554ced77ffb976352e8', max_length=64),
        ),
    ]
