# Generated by Django 5.2 on 2025-05-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0064_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='b5b8cf45c49e388d947d08bd5bce6c06', max_length=64),
        ),
    ]
