# Generated by Django 5.2 on 2025-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0066_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='f175686ed726bf66955e96ebb5db42c8', max_length=64),
        ),
    ]
