# Generated by Django 5.2 on 2025-05-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0067_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='cc2671c397dd50e9d6ec345465d1acb5', max_length=64),
        ),
    ]
