# Generated by Django 5.2 on 2025-05-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0068_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='a4557b1e4b353ac189005e145c183c4d', max_length=64),
        ),
    ]
