# Generated by Django 5.2 on 2025-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0069_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='a45909ab873e62877f5674d39db879c2', max_length=64),
        ),
    ]
