# Generated by Django 5.2 on 2025-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0070_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='3beb3271e6f10e41a1c6df18a68e41a4', max_length=64),
        ),
    ]
