# Generated by Django 5.2 on 2025-05-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0071_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='48514525d7cccac2bdf39ec8453e0af8', max_length=64),
        ),
    ]
