# Generated by Django 5.2 on 2025-05-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0072_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='2a91c9e806f1d2c39d1d6640514c1369', max_length=64),
        ),
    ]
