# Generated by Django 5.2 on 2025-05-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0074_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='48f03daa169e7f88e3ed3c1299a75242', max_length=64),
        ),
    ]
