# Generated by Django 5.2 on 2025-05-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0077_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='487a8436d3bab256a39e23024e6c1995', max_length=64),
        ),
    ]
