# Generated by Django 5.2 on 2025-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0078_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='520f9bcd7f07b1026393080a7b0f061b', max_length=64),
        ),
    ]
