# Generated by Django 5.2 on 2025-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0079_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='cc80faa84204460ca2adeab24d38ea59', max_length=64),
        ),
    ]
