# Generated by Django 5.2 on 2025-05-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0080_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='45f6a29d3f3e302628200cc92a637893', max_length=64),
        ),
    ]
