# Generated by Django 5.2 on 2025-05-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0081_alter_chat_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_message_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='system_message_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='50337f847be55d0cdbf2930c670449be', max_length=64),
        ),
    ]
