# Generated by Django 5.2 on 2025-05-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0082_message_system_message_params_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='7ae5b84777bd2000eb16a65a56ca29d8', max_length=64),
        ),
    ]
