# Generated by Django 5.2 on 2025-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0083_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='68e7f79e78c22f572e2e6cdbe4678a3d', max_length=64),
        ),
    ]
