# Generated by Django 5.2 on 2025-05-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0085_add_system_message_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='fe32964db1b12cde85e3dba03dae6224', max_length=64),
        ),
    ]
