# Generated by Django 5.2 on 2025-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0086_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='2e18c12581c543fed683b21f645d0ab5', max_length=64),
        ),
    ]
