# Generated by Django 5.2 on 2025-05-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0087_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='0b7f0c2c559fc643cb96fa20019d6b06', max_length=64),
        ),
    ]
