# Generated by Django 5.2 on 2025-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0088_alter_chat_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('kg', 'Kyrgyz')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='4e84a9aa8b2a54408386b5f50c63de03', max_length=64),
        ),
    ]
