# Generated by Django 5.2 on 2025-05-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0089_user_language_user_theme_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='fe42ef3f7bea95ad2cbf27085b20b20b', max_length=64),
        ),
    ]
