# Generated by Django 5.2 on 2025-05-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0090_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='bb9679b68f6449a7bc3d7f1344199658', max_length=64),
        ),
    ]
