# Generated by Django 5.2 on 2025-05-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0091_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='197dc3aafca02ec300af023452e686c2', max_length=64),
        ),
    ]
