# Generated by Django 5.2 on 2025-05-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0092_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='c63203d86c2f07a2b98f163a3f724910', max_length=64),
        ),
    ]
