# Generated by Django 5.2 on 2025-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0093_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='e2d269bbffc6c8cb2ecaacf54c21b158', max_length=64),
        ),
    ]
