# Generated by Django 5.2 on 2025-05-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0094_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='16863809ab694f554287ead0e34de0ae', max_length=64),
        ),
    ]
