# Generated by Django 5.2 on 2025-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0096_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='517223d56f9ee6477eebffd23eeaa2bf', max_length=64),
        ),
    ]
