# Generated by Django 5.2 on 2025-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0097_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='193e52ce9e2a56c49f9977bd102d6211', max_length=64),
        ),
    ]
