# Generated by Django 5.2 on 2025-05-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0098_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='9782849db20101df7af89404ab22f2f2', max_length=64),
        ),
    ]
