# Generated by Django 5.2 on 2025-05-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0099_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='d233f9247bc8772be405d5f96dac5bde', max_length=64),
        ),
    ]
