# Generated by Django 5.2 on 2025-05-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0100_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='0010f4442019b835046cfd8a7f45da12', max_length=64),
        ),
    ]
