# Generated by Django 5.2 on 2025-05-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0101_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='38d84e52bfbe093d392dca408530bc99', max_length=64),
        ),
    ]
