# Generated by Django 5.2 on 2025-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0102_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='198b2e96cbd6a81ade361c36e5f95735', max_length=64),
        ),
    ]
