# Generated by Django 5.2 on 2025-05-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0103_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='d4fc489bd48d23111f7788121c60c8ae', max_length=64),
        ),
    ]
