# Generated by Django 5.2 on 2025-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0105_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='57e777d6c5977bdd9b784fafeaf04e3e', max_length=64),
        ),
    ]
