# Generated by Django 5.2 on 2025-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0106_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='4a48874c8926c753a5091e811b61381c', max_length=64),
        ),
    ]
