# Generated by Django 5.2 on 2025-05-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0107_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='ff3150ccf22727a7759841375a236932', max_length=64),
        ),
    ]
