# Generated by Django 5.2 on 2025-05-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0108_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='79365cba3f7a805d1913cb8aa18e3227', max_length=64),
        ),
    ]
