# Generated by Django 5.2 on 2025-05-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0109_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='d88ffb0f9355ed0d7ce0188a3def6497', max_length=64),
        ),
    ]
