# Generated by Django 5.2 on 2025-05-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0110_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='5d5def5e88919124e2e6677412238b95', max_length=64),
        ),
    ]
