# Generated by Django 5.2 on 2025-05-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0111_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='c9bb825f7a9e1ecf716a0c0f60c10d49', max_length=64),
        ),
    ]
