# Generated by Django 5.2 on 2025-05-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0112_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='03bf275a0a237b1ebeb934ab340bbbce', max_length=64),
        ),
    ]
