# Generated by Django 5.2 on 2025-05-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0113_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='4c44b84acd9f99ae728324578ec4dfb6', max_length=64),
        ),
    ]
