# Generated by Django 5.2 on 2025-05-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0114_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='fce1e9c3b04350a140f91ef8a177359a', max_length=64),
        ),
    ]
