# Generated by Django 5.2 on 2025-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0115_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='86618bfde19406c8a615540081ca50ce', max_length=64),
        ),
    ]
