# Generated by Django 5.2 on 2025-05-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0116_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='6ed6fc2a917e673eec1488d371287696', max_length=64),
        ),
    ]
