# Generated by Django 5.2 on 2025-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0117_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='8f73d756a15194791c839e2bc34672f3', max_length=64),
        ),
    ]
