# Generated by Django 5.2 on 2025-05-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0118_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='98b0ee0654e9f6b6232fa5d9c45f3d8f', max_length=64),
        ),
    ]
