# Generated by Django 5.2 on 2025-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowsenger_backend', '0120_alter_chat_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='secret',
            field=models.CharField(default='3fa331087f2e34f720629aface534203', max_length=64),
        ),
    ]
